// <auto-generated />
using System;
using EcoWattCasa.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EcoWattCasa.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(EcoWattDbContext))]
    partial class EcoWattDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EcoWattCasa.Domain.Entities.Device", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("location");

                    b.Property<string>("MqttTopic")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("mqtt_topic");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("name");

                    b.Property<int>("NominalWatts")
                        .HasColumnType("integer")
                        .HasColumnName("nominal_watts");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_devices");

                    b.HasIndex("MqttTopic")
                        .IsUnique()
                        .HasDatabaseName("ix_devices_mqtt_topic");

                    b.ToTable("devices", (string)null);
                });

            modelBuilder.Entity("EcoWattCasa.Domain.Entities.EnergyReading", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<double>("Amperage")
                        .HasColumnType("double precision")
                        .HasColumnName("amperage");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<double?>("PowerFactor")
                        .HasColumnType("double precision")
                        .HasColumnName("power_factor");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamptz")
                        .HasColumnName("timestamp");

                    b.Property<double?>("TodayKwh")
                        .HasColumnType("double precision")
                        .HasColumnName("today_kwh");

                    b.Property<double?>("TotalKwh")
                        .HasColumnType("double precision")
                        .HasColumnName("total_kwh");

                    b.Property<double>("Voltage")
                        .HasColumnType("double precision")
                        .HasColumnName("voltage");

                    b.Property<double>("Watts")
                        .HasColumnType("double precision")
                        .HasColumnName("watts");

                    b.HasKey("Id")
                        .HasName("pk_energy_readings");

                    b.HasIndex("Timestamp")
                        .HasDatabaseName("ix_energy_readings_timestamp");

                    b.HasIndex("DeviceId", "Timestamp")
                        .HasDatabaseName("ix_energy_readings_device_timestamp");

                    b.ToTable("energy_readings", (string)null);
                });

            modelBuilder.Entity("EcoWattCasa.Domain.Entities.ImportedBill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("BasicAmount")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("basic_amount");

                    b.Property<int>("Days")
                        .HasColumnType("integer")
                        .HasColumnName("days");

                    b.Property<DateTimeOffset>("ImportedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("imported_at");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("invoice_number");

                    b.Property<double>("Kwh")
                        .HasColumnType("double precision")
                        .HasColumnName("kwh");

                    b.Property<double>("MeterEnd")
                        .HasColumnType("double precision")
                        .HasColumnName("meter_end");

                    b.Property<double>("MeterStart")
                        .HasColumnType("double precision")
                        .HasColumnName("meter_start");

                    b.Property<string>("Period")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("period");

                    b.Property<DateOnly>("ReadingFrom")
                        .HasColumnType("date")
                        .HasColumnName("reading_from");

                    b.Property<DateOnly>("ReadingTo")
                        .HasColumnType("date")
                        .HasColumnName("reading_to");

                    b.Property<decimal>("Total")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("total");

                    b.Property<decimal>("TotalTaxes")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("total_taxes");

                    b.HasKey("Id")
                        .HasName("pk_imported_bills");

                    b.HasIndex("InvoiceNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_imported_bills_invoice_number");

                    b.ToTable("imported_bills", (string)null);
                });

            modelBuilder.Entity("EcoWattCasa.Domain.Entities.TariffBlock", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("label");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("order");

                    b.Property<decimal>("PricePerKwh")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("price_per_kwh");

                    b.Property<Guid>("TariffScheduleId")
                        .HasColumnType("uuid")
                        .HasColumnName("tariff_schedule_id");

                    b.Property<double?>("UpToKwh")
                        .HasColumnType("double precision")
                        .HasColumnName("up_to_kwh");

                    b.HasKey("Id")
                        .HasName("pk_tariff_blocks");

                    b.HasIndex("TariffScheduleId", "Order")
                        .IsUnique()
                        .HasDatabaseName("ix_tariff_blocks_tariff_schedule_id_order");

                    b.ToTable("tariff_blocks", (string)null);
                });

            modelBuilder.Entity("EcoWattCasa.Domain.Entities.TariffPeriodCharge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("amount");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("name");

                    b.Property<Guid>("TariffScheduleId")
                        .HasColumnType("uuid")
                        .HasColumnName("tariff_schedule_id");

                    b.HasKey("Id")
                        .HasName("pk_tariff_period_charges");

                    b.HasIndex("TariffScheduleId")
                        .HasDatabaseName("ix_tariff_period_charges_tariff_schedule_id");

                    b.ToTable("tariff_period_charges", (string)null);
                });

            modelBuilder.Entity("EcoWattCasa.Domain.Entities.TariffSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<decimal>("FixedChargePerDay")
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("fixed_charge_per_day");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("source");

                    b.Property<DateOnly>("ValidFrom")
                        .HasColumnType("date")
                        .HasColumnName("valid_from");

                    b.HasKey("Id")
                        .HasName("pk_tariff_schedules");

                    b.HasIndex("ValidFrom")
                        .IsUnique()
                        .HasDatabaseName("ix_tariff_schedules_valid_from");

                    b.ToTable("tariff_schedules", (string)null);
                });

            modelBuilder.Entity("EcoWattCasa.Domain.Entities.TariffSurcharge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("name");

                    b.Property<decimal>("Rate")
                        .HasColumnType("numeric(8,5)")
                        .HasColumnName("rate");

                    b.Property<Guid>("TariffScheduleId")
                        .HasColumnType("uuid")
                        .HasColumnName("tariff_schedule_id");

                    b.HasKey("Id")
                        .HasName("pk_tariff_surcharges");

                    b.HasIndex("TariffScheduleId")
                        .HasDatabaseName("ix_tariff_surcharges_tariff_schedule_id");

                    b.ToTable("tariff_surcharges", (string)null);
                });

            modelBuilder.Entity("EcoWattCasa.Domain.Entities.EnergyReading", b =>
                {
                    b.HasOne("EcoWattCasa.Domain.Entities.Device", "Device")
                        .WithMany("Readings")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_energy_readings_devices_device_id");

                    b.Navigation("Device");
                });

            modelBuilder.Entity("EcoWattCasa.Domain.Entities.TariffBlock", b =>
                {
                    b.HasOne("EcoWattCasa.Domain.Entities.TariffSchedule", "TariffSchedule")
                        .WithMany("Blocks")
                        .HasForeignKey("TariffScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tariff_blocks_tariff_schedules_tariff_schedule_id");

                    b.Navigation("TariffSchedule");
                });

            modelBuilder.Entity("EcoWattCasa.Domain.Entities.TariffPeriodCharge", b =>
                {
                    b.HasOne("EcoWattCasa.Domain.Entities.TariffSchedule", "TariffSchedule")
                        .WithMany("PeriodCharges")
                        .HasForeignKey("TariffScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tariff_period_charges_tariff_schedules_tariff_schedule_id");

                    b.Navigation("TariffSchedule");
                });

            modelBuilder.Entity("EcoWattCasa.Domain.Entities.TariffSurcharge", b =>
                {
                    b.HasOne("EcoWattCasa.Domain.Entities.TariffSchedule", "TariffSchedule")
                        .WithMany("Surcharges")
                        .HasForeignKey("TariffScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tariff_surcharges_tariff_schedules_tariff_schedule_id");

                    b.Navigation("TariffSchedule");
                });

            modelBuilder.Entity("EcoWattCasa.Domain.Entities.Device", b =>
                {
                    b.Navigation("Readings");
                });

            modelBuilder.Entity("EcoWattCasa.Domain.Entities.TariffSchedule", b =>
                {
                    b.Navigation("Blocks");

                    b.Navigation("PeriodCharges");

                    b.Navigation("Surcharges");
                });
#pragma warning restore 612, 618
        }
    }
}
